imports:
  sklearn.linear_model :
    - ElasticNet
  sklearn.preprocessing:
    - StandardScaler
  classif:
    - AddMeta
  pyriemann.channelselection:
    - ElectrodeSelection
  pyriemann.estimation:
    - XdawnCovariances
  pyriemann.tangentspace:
    - TangentSpace
  
CrossVal:
  cores: 4
  folds: 4
  repetitions: 10
  path: results.csv
  comments: 'model-final-noLeak'

Submission:
  path: submission-noLeak.csv
  cores: 4

MetaPipeline:
  #leak:
  bagging:
     bag_size: 0.51 # % of subjects to train on in each bagged model. If bag_size==1 then LOSO bagging is performed 
     models: 500 # ignored for LOSO bagging

pipeline:
  - XdawnCovariances:
      nfilter: 5
  - TangentSpace:
      metric: "'riemann'"
      tsupdate: False
  - StandardScaler:
  - ElasticNet:
      l1_ratio: 0.5
      alpha: 2e-4
